server:
  port: 8086

spring:
  application:
    name: recommendation-service
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/product_db
    username: ecommerce
    password: ecommerce123
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    dev.makeev.recommendation: DEBUG
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
