server:
  port: 8083

spring:
  application:
    name: cart-service
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    dev.makeev.cart: DEBUG
    org.springframework.data.redis: DEBUG
    reactor.netty: INFO
